<%@ Page Title="" Language="C#" MasterPageFile="~/FrontMasterPage.master" AutoEventWireup="true" CodeFile="AboutUs.aspx.cs" Inherits="AboutUs" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
   
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div class="row">
        <div class="col-12 m-0 p-0">
            <img src="Image/about_us1.jpg" alt="" class="img-fluid" style="" />
        </div>
    </div>
   
        <div class="row mt-5 mb-5">
            
            <div class="col-lg-6 col-sm-12"><img src="Image/slider4.jpg" class="img-fluid" /></div>
            <div class="col-lg-6 col-sm-12" style="text-align:justify;font-family: 'Philosopher', sans-serif;">
               <b style="color:#003a6a;">National Paramedical council And Vocational Board Skill Development, INDIA</b> is an Autonomous body for Industrial and Vocational Education and Training. All Technical And Vocational Education to all class of people in a very reasonable fees structure. National Paramedical Council And Vocational Board Skill Development  also offers reasonable fees structure for financially weaker section who cannot afford the same. National Paramedical Council And Vocational Board Skill Development regularly organized, workshops, seminars, conventions and Technical for the benefit of professionals and users of IT apart from conducting continuing education and professional development programmes for a focused audiences of budding professionals researchers and students.<br />
The annual conventions are held in Different cities across India. National Paramedical Council And Vocational Board Skill Development also extends funding support for computer, Paramedical, Technical  research projects as well as funds visits of researchers presenting papers at National conferences. The activities conducted for the students associated with the society include sectors meeting, seminars, conferences, training programs, programming

            </div>
            <div class="col-12" style="text-align:justify;font-family: 'Philosopher', sans-serif;">
                  controls and practical visits to installation.<br />
                 In the ever changing environment. National Paramedical Council And Vocational Board Skill Development offers professional counseling being a great need of the hour and this is done by being in closed control with its young members through various events conferences symposia to name a few. Furthermore as computer/technical education in schools plays important role in students career development. Computer with the internet is the most powerful device that students can use to learn new skills and more advanced version of current lessons. The uses of computer and internet are growing day by day at high speed. In almost all businesses companies schools using computers for various official operations.
                <br />
National Paramedical Council And Vocational Board Skill Development is the platform for unchanging the able and for better career opportunities. Here we assure the bright future of candidate in the computer education. In the current word it is almost impossible to imagine that someone can live without computers. They have become an electronic device of almost everyday use for individuals of every age and essential in almost call the business dealing that are made nowadays. So to provide all the education regarding computers to all the students. National Paramedical Council And Vocational Board Skill Development Board successfully running many centres all over India which focus on success of the candidate with the updated Technology and fertility in India and therefore National Paramedical Council And Vocational Board Skill Development is successfully running many centres all over India and its franchises.<br />
                Mainly a Non-Governmental Organization Incorporated under Section 8 of the Companies Act. 2013 (Section 25 of Previous Companies Act. 1956) by Ministry of Corporate Affairs, Govt. of India is mainly working in the area of Education, Health Care for Under privileged Children of the society, Women and other community members living in difficult circumstances-children of -daily wage, migrant child Labour,s from rural / tribal areas. We focus on Educational Development Worldwide and career counseling for holistic development and facilitating gainful employment after vocational training to youth and woman is integral part of our programs.

</div>
            <div class="col-lg-6 col-sm-12"  style="text-align:justify;font-family: 'Philosopher', sans-serif;">
               
We are a Leading Educational Development Network in all States and Union Territories of India and globally, we control Manage and Run all the Affiliated Organizations or Authorized Study and Training Centre’s from the Head office only. <b style="color:#003a6a;"> NATIONAL PARAMEDICAL COUNCIL AND VOCATIONAL BOARD SKILL DEVELOPMENT </b> is a Non Profit  making Organization with the mission to spread over the Industrial and Vocational Education e.g. Computer  Literacy  and Information Science Programs, Technical Courses, Management Education, English Spoken, Medical and Health Courses, Yoga Training, Journalism  and Mass Communication Education, Naturopathy and Ayurveda Education, Human Right Education, Social Development Education for Rural and Urban Society of the nation, Early Childhood care  Education, Sports and physical education and  the  develop  the  soft skills  in  each  and  every  person with a view to expand our mission we have launched 3840+ Industrial and vocational courses which are helpful in self-employment. Moreover for providing the best opportunities to the students and Centre Directors, we have launched a transparent, user friendly and responsive website. 
            </div>
            <div class="col-lg-6 col-sm-12"><img src="Image/slider4.jpg" class="img-fluid" /></div>
            <div class="col-12" style="text-align:justify;font-family: 'Philosopher', sans-serif;">
                There are various cooperative Academic Divisions and Associates are working globally. And association with the top ranking national and international universities, Government Non-Government organizations and public authorities we always try best to achieve the goal of Educational Development in India. We are also <b style="color:#003a6a;">An ISO 9001:2015 Educational Certified Organization in Quality Management System Running Educational Services</b> Successfully.Our main aim to provide adequate education and training for educational development in India as deep and adequate knowledge.
                <br />
                Our team always focuses on to bring out and built the personality of the student to change life-style by new technologies and providing awareness to upcoming technologies and changing environment. Our all Academic Divisions providing course and Training Programs at very nominal and affordable fees also launched specially unpaid category courses as possible. We Provides very nominal and lowest Fees OR Free Training to the people who belongs to Lower category/SC/ST/OBC/BPL/Widow and Physically Challenges, according NPCVB’s norms and State and Central Government Regulations.For help students to learn computer and other required skills or other Job Oriented Training Courses we always support to students in regular and distance education and training,Our aim to launch this Organization is to promote education in India by way of various courses which are relevant to the current time through qualified, experienced teachers and professionals enable the student, to become self-dependent, and which are job oriented Vocational training and establish, manage, maintain and run educational, vocational and technical institutions in India.
                <br />
                The main function of the <b style="color:#003a6a;"> National Paramedical Council And Vocational Board Skill Development</b> is to provide higher technical and non-technical education in nominal charges for every group of organization of Urban & Rural areas all over India and get success in Industrial and Vocational revolution which is the main dream Govt. of India. With Support of Various public Authorities to grant scholarship or provide financial aid to poor/ meritorious students in the field of education and undertake other allied educational activity and organized promotional events related to the education, we communicate and engage with the Government, local and public authorities related with education, and Non-Government Organization on any subject related with education. Provide assistance to any Organization, individual or group of people in furtherance of the object of the society. None of the objects of the Organization carried out on commercial basis.
        </div>
    </div>
</asp:Content>

